In [1]:
import numpy as np

In [3]:
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


arange([start],stop,[step])
Stopping number is not included in the list

In [4]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
A = np.array([1, 2, 3, 4])
print(A.shape)

(4,)


In [13]:
A.reshape(1,4)

array([[1, 2, 3, 4]])

In [14]:
A.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Multiplication

In [19]:
I = np.eye(3)
D = np.arange(1,10).reshape(3,3)
M = np.dot(I,D)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Adding elements of a matric

In [21]:
# Sum along rows
np.sum(M, axis = 1)

array([ 6., 15., 24.])

In [22]:
# Sum along columns
np.sum(M, axis= 0)

array([12., 15., 18.])

Random Numbers

In [23]:
np.random.rand(2,3)

array([[0.23729441, 0.74265837, 0.13954651],
       [0.32713078, 0.36706103, 0.06767023]])

In [26]:
A = np.arange(5,15,2)
A = np.append(A,19)
A

array([ 5,  7,  9, 11, 13, 19])

Difference between adjacent elements

In [30]:
B = np.diff(A,n=1)
B
C = np.diff(A, n=2)
C

array([0, 0, 0, 4])

Stacking lists as a matrix/vector

In [31]:
a = [1,2,3]
b = [4,5,6]
c= [7,8,9]

In [32]:
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Slicing

A[lowerbound(inclusive) : upperbound(exclusive)]

In [4]:
import numpy as np
A = np.arange(1,10)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
A[2:5]

array([3, 4, 5])

In [6]:
print(A[2:6])
print(A[:6])
print(A[5:])

[3 4 5 6]
[1 2 3 4 5 6]
[6 7 8 9]


Broadcating operations

In [41]:
print(A)
A+=1
A

[ 4  5  6  7  8  9 10 11 12]


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

## Running a 2 layer Neural Net with Numpy

In [1]:
import numpy as np

# Batch size, input dimensions, hidden dimension, output dimension
N, D_in, H, D_out = 64, 1000, 100, 10

# Random input and output
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Random initial weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):
    
    #Forward
    h = x.dot(w1)
    h_relu = np.maximum(h,0)
    y_pred = h_relu.dot(w2)
    
    
    # Loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    # Backprop
    grad_y_pred = 2.0 * (y_pred - y)
    # T = transpose
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h<0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2
    

0 32607380.348142628
1 29506117.24819856
2 29767040.37727147
3 28408740.072652444
4 23565785.84954831
5 16200799.995617874
6 9681304.646141466
7 5360852.982607686
8 3054352.4465844054
9 1897481.5809097732
10 1314184.4253778784
11 994177.9702514554
12 797983.037458092
13 663393.7257756023
14 563140.2726165527
15 484365.3995086545
16 420214.42693857965
17 366814.3627315778
18 321790.19534978294
19 283517.987866234
20 250749.94877574252
21 222539.15015767294
22 198163.03478178405
23 176970.29187239622
24 158490.25093734713
25 142319.06534885673
26 128109.49431677363
27 115584.28906755181
28 104510.095185991
29 94687.29775832836
30 85948.71345109469
31 78154.8018473312
32 71189.30141981477
33 64951.50751211075
34 59350.944173457625
35 54313.235141510304
36 49775.837352444214
37 45682.02189750914
38 41978.3949738316
39 38633.5121935317
40 35603.12365466941
41 32849.051643912266
42 30346.561494168163
43 28067.941150402003
44 25990.375291590608
45 24090.693252103374
46 22350.227908084686
47 2